<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright The RESTEasy Authors
  ~ SPDX-License-Identifier: Apache-2.0
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>dev.resteasy.jetty</groupId>
        <artifactId>resteasy-jetty-parent</artifactId>
        <version>1.0.0.Alpha3-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>resteasy-jetty-project-bom</artifactId>
    <packaging>pom</packaging>
    <name>RESTEasy Jetty: BOM for Project Dependencies</name>

    <properties>
        <!-- Dependency versions -->
        <version.jakarta.ee>11.0.0</version.jakarta.ee>
        <version.org.eclipse.jetty>12.1.12</version.org.eclipse.jetty>
        <version.org.jboss.logging>3.6.3.Final</version.org.jboss.logging>
        <version.org.jboss.resteasy>7.0.3.Final</version.org.jboss.resteasy>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>jakarta.platform</groupId>
                <artifactId>jakarta.jakartaee-bom</artifactId>
                <version>${version.jakarta.ee}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-bom</artifactId>
                <version>${version.org.eclipse.jetty}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>dev.resteasy.jetty</groupId>
                <artifactId>resteasy-jetty-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.jboss.resteasy</groupId>
                <artifactId>resteasy-bom</artifactId>
                <version>${version.org.jboss.resteasy}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

            <dependency>
                <groupId>org.jboss.logging</groupId>
                <artifactId>jboss-logging</artifactId>
                <version>${version.org.jboss.logging}</version>
            </dependency>
            <dependency>
                <groupId>org.kohsuke.metainf-services</groupId>
                <artifactId>metainf-services</artifactId>
                <version>${version.org.kohsuke.metainf-services}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
