<!--
  ~ Copyright The RESTEasy Authors
  ~ SPDX-License-Identifier: Apache-2.0
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">

    <parent>
        <groupId>org.jboss</groupId>
        <artifactId>jboss-parent</artifactId>
        <version>53</version>
        <relativePath />
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <name>RESTEasy Jetty Integration</name>
    <description>RESTEasy integration for Eclipse Jetty</description>

    <groupId>dev.resteasy.jetty</groupId>
    <artifactId>resteasy-jetty-parent</artifactId>
    <version>1.0.0.Alpha3-SNAPSHOT</version>
    <packaging>pom</packaging>
    <url>https://resteasy.dev</url>

    <organization>
        <name>RESTEasy Community</name>
        <url>https://resteasy.dev</url>
    </organization>
    <licenses>
        <license>
            <name>Apache License 2.0</name>
            <url>https://repository.jboss.org/licenses/apache-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>jamezp</id>
            <name>James R. Perkins</name>
            <email>jperkins@ibm.com</email>
            <organization>IBM</organization>
            <roles>
                <role>project-owner</role>
            </roles>
            <timezone>-8</timezone>
        </developer>
    </developers>

    <modules>
        <module>bom/bom</module>
        <module>bom/project-bom</module>
        <module>bom/test-bom</module>
        <module>client</module>
        <module>embedded-server</module>
        <module>docs</module>
    </modules>

    <scm>
        <connection>scm:git:git://github.com/resteasy/resteasy-jetty.git</connection>
        <developerConnection>scm:git:git@github.com:resteasy/resteasy-jetty.git</developerConnection>
        <url>https://github.com/resteasy/resteasy-jetty/tree/main/</url>
      <tag>HEAD</tag>
  </scm>

    <issueManagement>
        <system>GitHub Issues</system>
        <url>https://github.com/resteasy/resteasy-jetty/issues</url>
    </issueManagement>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- Compile to Java 17 -->
        <maven.compiler.release>17</maven.compiler.release>

        <!-- print logs to file by default -->
        <maven.test.redirectTestOutputToFile>true</maven.test.redirectTestOutputToFile>

        <!-- Dependency versions -->
        <version.org.jboss.resteasy>7.0.3.Final</version.org.jboss.resteasy>
        <version.org.kohsuke.metainf-services>1.11</version.org.kohsuke.metainf-services>

        <!-- Plugins versions -->
        <version.spotless-maven-plugin>3.10.1</version.spotless-maven-plugin>

        <!-- maven-release-plugin configuration -->
        <autoVersionSubmodules>true</autoVersionSubmodules>
        <releaseProfiles>central-release</releaseProfiles>
        <signTag>true</signTag>
        <tagNameFormat>v@{project.version}</tagNameFormat>
        <arguments>-DskipTests -DpushChanges=${pushChanges} -Dcentral.autoPublish=${central.autoPublish}</arguments>
        <!-- Do not push changes by default when using the maven-release-plugin:prepare -->
        <pushChanges>false</pushChanges>
        <!-- Use the local directory when using perform -->
        <localCheckout>true</localCheckout>
        <!-- Maven Central properties -->
        <central.deploymentName>resteasy-jetty-${project.version}</central.deploymentName>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <executions>
                    <execution>
                        <id>check-style</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>checkstyle</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.kohsuke.metainf-services</groupId>
                            <artifactId>metainf-services</artifactId>
                            <version>${version.org.kohsuke.metainf-services}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>ban-bad-dependencies</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <bannedDependencies>
                                    <searchTransitive>true</searchTransitive>
                                    <excludes>
                                        <exclude>javax.*:*</exclude>
                                        <exclude>log4j:log4j</exclude>
                                    </excludes>
                                </bannedDependencies>
                            </rules>
                        </configuration>
                    </execution>
                    <execution>
                        <id>dep-convergence</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <dependencyConvergence />
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${version.spotless-maven-plugin}</version>
                <dependencies>
                    <dependency>
                        <groupId>dev.resteasy.tools</groupId>
                        <artifactId>ide-config</artifactId>
                        <version>4</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <upToDateChecking>
                        <enabled>true</enabled>
                        <indexFile>${project.basedir}/.cache/spotless-index-${version.spotless-maven-plugin}</indexFile>
                    </upToDateChecking>
                    <java>
                        <eclipse>
                            <file>eclipse-code-formatter.xml</file>
                        </eclipse>
                        <importOrder>
                            <order>\#,java,javax,jakarta,org,io,dev,com,net</order>
                        </importOrder>
                        <removeUnusedImports>
                            <!-- default one fails to process the classes -->
                            <engine>cleanthat-javaparser-unnecessaryimport</engine>
                        </removeUnusedImports>
                        <forbidWildcardImports />
                        <trimTrailingWhitespace />
                        <endWithNewline />
                        <licenseHeader>
                            <file>license-java-asl-header</file>
                            <!-- Delimiter is a regex which identifies the "top" of the file i.e. all above it is considered a header -->
                            <delimiter>(\n)*^(\/\/tag.+|\/\/spotless.+|package .+;|module .+;|\/\/.+|\/\*\*.*)$</delimiter>
                        </licenseHeader>
                        <replaceRegex>
                            <name>Remove wildcard imports</name>
                            <searchRegex>^import\s+[^\*\s]+\*;$</searchRegex>
                            <replacement>$1</replacement>
                        </replaceRegex>
                    </java>
                    <formats>
                        <format>
                            <includes>
                                <include>pom.xml</include>
                                <include>src/**/*.xml</include>
                            </includes>
                            <trimTrailingWhitespace />
                            <endWithNewline />
                            <licenseHeader>
                                <file>license-xml-asl-header</file>
                                <!-- Delimiter is a regex which identifies the "top" of the file i.e. all above it is considered a header -->
                                <delimiter><![CDATA[(\n)*^(<[^!?]+|<!DOCTYPE.+)$]]></delimiter>
                                <skipLinesMatching><![CDATA[<\?xml.+\?>]]></skipLinesMatching>
                            </licenseHeader>
                            <indent>
                                <spaces>true</spaces>
                                <spacesPerTab>4</spacesPerTab>
                            </indent>
                        </format>
                    </formats>
                    <asciidoc>
                        <includes>
                            <include>**/*.adoc</include>
                        </includes>

                        <adocfmt>
                            <normalizeListBullets>true</normalizeListBullets>
                            <normalizeOrderedListMarkers>true</normalizeOrderedListMarkers>
                            <ensureSourceDelimiters>true</ensureSourceDelimiters>
                        </adocfmt>
                    </asciidoc>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>apply</goal>
                        </goals>
                        <phase>process-sources</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>format-check</id>
            <build>
                <plugins>
                    <!-- Validate formatting -->
                    <plugin>
                        <groupId>com.diffplug.spotless</groupId>
                        <artifactId>spotless-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>validate-format</id>
                                <phase>validate</phase>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>debug-logs</id>
            <activation>
                <property>
                    <name>debug.logs</name>
                </property>
            </activation>
            <properties>
                <maven.test.redirectTestOutputToFile>false</maven.test.redirectTestOutputToFile>
            </properties>
        </profile>
    </profiles>
</project>
